### PR TITLE
Add a buildkite worker image for FreeBSD

### PR DESCRIPTION
**Pull request by ararslan**
Most things are copy-pasta'd and edited from the Windows KVM buildkite worker. I have no idea what I'm doing, tbh. I realized that some of the setup scripts require running as root (or for the user to have passwordless `sudo`) but I explicitly disabled ssh root login in the base image. @staticfloat, would you be willing to provide some sagely guidance to set me in the right direction here?

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ararslan @staticfloat What still needs to be done here?

**Comment by ararslan** [comment]
Elliot mentioned on Slack that he was going to revisit this after the improvements to the Windows KVM setup in #22 had landed. I should be able to revisit this this weekend, hopefully I can grab some of Elliot's time/wisdom to figure out what the right path forward is.

**Comment by ararslan** [comment]
I copied the symlinking pattern used for Windows that was just removed by #29 so I'll update that as well.

**Comment by ararslan** [comment]
@staticfloat, I think this is ready for review. Could you take a look when you get a chance?

**Comment by ararslan** [comment]
In case it's useful for review, here's a diff between the files added/modified here and their Windows equivalents.

How the diff was generated:

```julia
for file in eachline(`git diff --name-only origin/main`)
    windows = replace(file, "freebsd" => "windows")
    if basename(file) == "README.md" || !isfile(windows)
        continue
    end
    run(`git --no-pager diff HEAD:$windows $file`)
end
```

Files compared:
- `freebsd-kvm/base-image/Makefile`
- `freebsd-kvm/buildkite-worker/.gitignore`
- `freebsd-kvm/buildkite-worker/Makefile`
- `freebsd-kvm/buildkite-worker/common.jl`
- `freebsd-kvm/buildkite-worker/config.toml.example`
- `freebsd-kvm/buildkite-worker/kvm_machine.pkr.hcl.template`
- `freebsd-kvm/buildkite-worker/kvm_machine.xml.template`
- `freebsd-kvm/buildkite-worker/launch_agents.jl`
- `freebsd-kvm/buildkite-worker/uninstall_agents.jl`
- `freebsd-kvm/debug/.gitignore`
- `freebsd-kvm/debug/Makefile`
- `freebsd-kvm/debug/common.jl`
- `freebsd-kvm/debug/kvm_machine.pkr.hcl.template`
- `freebsd-kvm/debug/kvm_machine.xml.template` (This was manually excluded from the diff. For FreeBSD it's a symlink to the file in `buildkite-worker` and for Windows it's a copy.)
- `freebsd-kvm/debug/launch_agents.jl`
- `freebsd-kvm/debug/uninstall_agents.jl`


<details><summary>Click to expand the diff</summary>

```diff
diff --git a/windows-kvm/base-image/Makefile b/freebsd-kvm/base-image/Makefile
index 6bf548f..9a19ed8 100644
--- a/windows-kvm/base-image/Makefile
+++ b/freebsd-kvm/base-image/Makefile
@@ -8,7 +8,6 @@ endif
 endef
 
 # Check for necessary tools
-$(eval $(call check_tool,7z))
 $(eval $(call check_tool,packer))
 $(eval $(call check_tool,mkisofs))
 $(eval $(call check_tool,qemu-system-x86_64))
@@ -25,20 +24,10 @@ $(eval $(call check_group,libvirt))
 
 all: build
 
-downloads virtio-win:
-	mkdir -p "$@"
-
-downloads/virtio-win.iso: | downloads
-	curl -L -o "$@" "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.221-1/virtio-win.iso"
-
-virtio-win/virtio-win-guest-tools.exe: downloads/virtio-win.iso | virtio-win
-	cd virtio-win && 7z x "../$<"
-	touch -m "$@"
-
-images/%.qcow2: %.pkr.hcl $(SECRET_VARIABLES_FILE) | virtio-win/virtio-win-guest-tools.exe
+images/%.qcow2: %.pkr.hcl $(SECRET_VARIABLES_FILE)
 	packer build $(PACKER_ARGS) $<
 
-build: images/windows_server_2022.qcow2
+build: images/freebsd12.qcow2
 
 validate: $(SECRET_VARIABLES_FILE)
 	for f in *.pkr.hcl; do \
@@ -49,5 +38,4 @@ validate: $(SECRET_VARIABLES_FILE)
 clean:
 	rm -rf images
 
-cleanall:
-	rm -rf images virtio-win
+cleanall: clean
diff --git a/windows-kvm/buildkite-worker/common.jl b/freebsd-kvm/buildkite-worker/common.jl
index b192bd1..8451f48 100644
--- a/windows-kvm/buildkite-worker/common.jl
+++ b/freebsd-kvm/buildkite-worker/common.jl
@@ -43,7 +43,7 @@ function build_packer_images(brgs::Vector{BuildkiteRunnerGroup})
     end
     buildkite_agent_token = strip(String(read(buildkite_agent_token_path)))
 
-    packer_secrets_file = joinpath(repo_root, "secrets", "windows-credentials.pkrvars.hcl")
+    packer_secrets_file = joinpath(repo_root, "secrets", "credentials.pkrvars.hcl")
     if !isfile(packer_secrets_file)
         error("Must fill out $(packer_secrets_file)")
     end
@@ -53,19 +53,11 @@ function build_packer_images(brgs::Vector{BuildkiteRunnerGroup})
     agent_idx = 0
     brgs = sort(brgs, by=brg -> brg.name)
     for brg in brgs
-        # Ensure that we have a `source_image` type set
-        local source_image
-        if brg.source_image == "standard"
-            source_image = joinpath(dirname(@__DIR__), "base-image", "images", "windows_server_2022.qcow2")
-        elseif brg.source_image == "core"
-            source_image = joinpath(dirname(@__DIR__), "base-image", "images", "windows_server_2022_core.qcow2")
-        else
-            error("Runner group $(brg.name) must define a valid source image type!")
-        end
+        source_image = joinpath(dirname(@__DIR__), "base-image", "images", "freebsd12.qcow2")
 
-        # Ensure that we have `os` set to `windows`
-        if brg.tags["os"] != "windows"
-            error("Refusing to start up a windows KVM runner that does not self-identify through tags!")
+        # Ensure that we have `os` set to `freebsd`
+        if brg.tags["os"] != "freebsd"
+            error("Refusing to start up a FreeBSD KVM runner that does not self-identify through tags!")
         end
 
         tags_with_queues = ["$tag=$value" for (tag, value) in brg.tags]
@@ -121,7 +113,7 @@ function generate_systemd_script(io::IO, brg::BuildkiteRunnerGroup;
     start_pre_hooks = SystemdTarget[
         SystemdBashTarget("mkdir -p $(agent_scratch_dir(agent_hostname))")
     ]
-     
+
     # If we have buildkite queues, we automatically make this an ephemeral VM
     # and will reset it to pristine after each shutdown
     if !isempty(brg.queues)
diff --git a/windows-kvm/buildkite-worker/config.toml.example b/freebsd-kvm/buildkite-worker/config.toml.example
index 7bfab18..f86f7e4 100644
--- a/windows-kvm/buildkite-worker/config.toml.example
+++ b/freebsd-kvm/buildkite-worker/config.toml.example
@@ -1,12 +1,9 @@
 # We define groups of workers by name, each with their own configuration:
-[win2k22]
+[freebsd12]
 # Note that `queue` is a comma-separated list of queues
 queues="default"
 num_agents=2
 
-# source_image can be either `standard` or `core`
-source_image="standard"
-
-[win2k22.tags]
-# Manually override this to say `windows`, even though we're on a linux host
-os="windows"
\ No newline at end of file
+[freebsd12.tags]
+# Manually override this to say `freebsd`, even though we're on a linux host
+os="freebsd"
diff --git a/windows-kvm/buildkite-worker/kvm_machine.pkr.hcl.template b/freebsd-kvm/buildkite-worker/kvm_machine.pkr.hcl.template
index ab6b1e2..e0ae084 100644
--- a/windows-kvm/buildkite-worker/kvm_machine.pkr.hcl.template
+++ b/freebsd-kvm/buildkite-worker/kvm_machine.pkr.hcl.template
@@ -1,11 +1,10 @@
 variable "os_disk_size" {
     type = number
-    # Use 60G by default; this should match the base-image
     default = 60
 }
+
 variable "data_disk_size" {
     type = number
-    # Use 100G by default, for mucho caching
     default = 100
 }
 
@@ -13,71 +12,57 @@ variable "username" {
     type = string
     default = "julia"
 }
+
 variable "password" {
     type = string
     sensitive = true
 }
 
-source "qemu" "windows_server_2022" {
-    # Make sure this is accelerated by KVM
-    accelerator       = "kvm"
-
-    # Use WinRM as the communicator
-    communicator      = "winrm"
-    winrm_username    = "Administrator"
-    winrm_password    = var.password
-    winrm_timeout     = "120m"
-
-    # Use the base image built previously
-    iso_checksum      = "none"
-    disk_image        = true
-    use_backing_file  = true
-
-    # Include our setup scripts as another CD (E:/)
-    cd_files          = [
-        "setup_scripts",
-        "../../secrets",
-        "../../hooks",
-    ]
+source "qemu" "freebsd12" {
+    iso_url = "file:${source_image}"
+    iso_checksum = "none"
+    disk_image = true
+    use_backing_file = true
 
-    # Spit this out into `images`
-    output_directory  = "images/${agent_hostname}"
+    output_directory = "images/${agent_hostname}"
+    accelerator = "kvm"
+    headless = true
 
-    # Hardware/execution parameters
-    cpus                 = 2
-    memory               = 8196
-    disk_size            = "${var.os_disk_size}G"
+    cpus = 2
+    memory = 8196
+    disk_size = "${var.os_disk_size}G"
     disk_additional_size = ["${var.data_disk_size}G"]
-    headless             = true
 
-    # Turn on VNC password so that Apple VNC clients can connect
-    vnc_use_password  = true
+    communicator = "ssh"
+    username = var.username
+    password = var.password
 
-    # Once we're done provisioning, use this to shut down the VM
-    shutdown_command  = "shutdown /s /t 1 /f /d p:4:1 /c \"Packer Shutdown\""
+    vnc_use_password = true
+    shutdown_command = "shutdown -p now"
+
+    vm_name = "${agent_hostname}.qcow2"
 }
 
 build {
-    source "qemu.windows_server_2022" {
-        vm_name = "${agent_hostname}.qcow2"
-        iso_url = "file:${source_image}"
-    }
+    sources = ["source.qemu.freebsd12"]
 
-    provisioner "powershell" {
+    provisioner "shell" {
         environment_vars = [
-            "WINDOWS_PASSWORD=${var.password}",
-            "sanitized_hostname=${sanitized_agent_hostname}",
-
-            # These get auto-populated (see https://raw.githubusercontent.com/buildkite/agent/main/install.ps1)
-            "buildkiteAgentToken=${buildkite_agent_token}",
-            "buildkiteAgentTags=${buildkite_tags}",
-            "buildkiteAgentQueues=${buildkite_queues}",
-
-            # These don't currently get auto-replaced, but someday they might!
-            "buildkiteAgentName=${agent_hostname}",
+            "BUILDKITE_AGENT_NAME=${agent_hostname}",
+            "BUILDKITE_AGENT_QUEUES=${buildkite_queues}"
+            "BUILDKITE_AGENT_TAGS=${buildkite_tags}",
+            "SANITIZED_HOSTNAME=${sanitized_agent_hostname}",
+            "TOKEN=${buildkite_agent_token}",
+            "USERNAME=${var.username}",
+        ]
+        execute_command = "chmod +x {{ .Path }}; env {{ .Vars }} {{ .Path }}"
+        scripts = [
+            "setup_scripts/format-data-disk.sh",
+            "setup_scripts/set-hostname.sh",
+            "setup_scripts/install-buildkite-agent.sh",
+            "setup_scripts/install-wireguard.sh",
+            "setup_scripts/install-telegraf.sh",
+            "setup_scripts/install-zstd.sh",
         ]
-        inline = [". D:\\setup_scripts\\setup.ps1"]
-        elevated_user = var.username
-        elevated_password = var.password
     }
 }
diff --git a/windows-kvm/buildkite-worker/kvm_machine.xml.template b/freebsd-kvm/buildkite-worker/kvm_machine.xml.template
index a3b5257..f9f7da0 100644
--- a/windows-kvm/buildkite-worker/kvm_machine.xml.template
+++ b/freebsd-kvm/buildkite-worker/kvm_machine.xml.template
@@ -2,7 +2,7 @@
   <name>${agent_hostname}</name>
   <metadata>
     <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
-      <libosinfo:os id="http://microsoft.com/win/2k22"/>
+      <libosinfo:os id="http://freebsd.org/freebsd/12.2"/>
     </libosinfo:libosinfo>
   </metadata>
   <memory unit='KiB'>${memory_kb}</memory>
diff --git a/windows-kvm/debug/kvm_machine.pkr.hcl.template b/freebsd-kvm/debug/kvm_machine.pkr.hcl.template
index ed58b25..ae70d97 100644
--- a/windows-kvm/debug/kvm_machine.pkr.hcl.template
+++ b/freebsd-kvm/debug/kvm_machine.pkr.hcl.template
@@ -1,6 +1,5 @@
 variable "os_disk_size" {
     type = number
-    # Use 60G by default; this should match the base-image
     default = 60
 }
 
@@ -8,61 +7,53 @@ variable "username" {
     type = string
     default = "julia"
 }
+
 variable "password" {
     type = string
     sensitive = true
 }
 
-source "qemu" "windows_server_2022" {
-    # Make sure this is accelerated by KVM
-    accelerator       = "kvm"
-
-    # Use WinRM as the communicator
-    communicator      = "winrm"
-    winrm_username    = "Administrator"
-    winrm_password    = var.password
-    winrm_timeout     = "120m"
-
-    # Use the base image built previously
-    iso_checksum      = "none"
-    disk_image        = true
-    use_backing_file  = true
+source "qemu" "freebsd12" {
+    iso_url = "file:${source_image}"
+    iso_checksum = "none"
+    disk_image = true
+    use_backing_file = true
 
-    # Include our setup scripts as another CD (E:/)
-    cd_files          = [
-        "setup_scripts",
-        "../../secrets/wireguard_keys",
-    ]
+    output_directory = "images/${agent_hostname}"
+    accelerator = "kvm"
+    headless = true
 
-    # Spit this out into `images`
-    output_directory  = "images/${agent_hostname}"
+    cpus = 2
+    memory = 8196
+    disk_size = "${var.os_disk_size}G"
 
-    # Hardware/execution parameters
-    cpus                 = 2
-    memory               = 8196
-    disk_size            = "${var.os_disk_size}G"
-    headless             = true
+    communicator = "ssh"
+    username = var.username
+    password = var.password
 
-    # Turn on VNC password so that Apple VNC clients can connect
-    vnc_use_password  = true
+    vnc_use_password = true
+    shutdown_command = "shutdown -p now"
 
-    # Once we're done provisioning, use this to shut down the VM
-    shutdown_command  = "shutdown /s /t 1 /f /d p:4:1 /c \"Packer Shutdown\""
+    vm_name = "${agent_hostname}.qcow2"
 }
 
 build {
-    source "qemu.windows_server_2022" {
-        vm_name = "${agent_hostname}.qcow2"
-        iso_url = "file:${source_image}"
-    }
+    sources = ["source.qemu.freebsd12"]
 
-    provisioner "powershell" {
+    provisioner "shell" {
         environment_vars = [
-            "WINDOWS_PASSWORD=${var.password}",
-            "sanitized_hostname=${sanitized_agent_hostname}",
+            "BUILDKITE_AGENT_NAME=${agent_hostname}",
+            "BUILDKITE_AGENT_QUEUES=${buildkite_queues}"
+            "BUILDKITE_AGENT_TAGS=${buildkite_tags}",
+            "SANITIZED_HOSTNAME=${sanitized_agent_hostname}",
+            "TOKEN=${buildkite_agent_token}",
+            "USERNAME=${var.username}",
+        ]
+        execute_command = "chmod +x {{ .Path }}; env {{ .Vars }} {{ .Path }}"
+        scripts = [
+            "setup_scripts/install-julia.sh",
+            "setup_scripts/set-hostname.sh",
+            "setup_scripts/install-wireguard.sh",
         ]
-        inline = [". D:\\setup_scripts\\setup.ps1"]
-        elevated_user = var.username
-        elevated_password = var.password
     }
 }
```

</details>

**Pull request merged**
